run:
  timeout: 5m
  skip-files:
    - ".*\\.pb\\.go$"
  allow-parallel-runners: true
  go: '1.24'

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  revive:
    severity: warning
    confidence: 0.8
  gocritic:
    enabled-tags:
      - performance
  goimports:
    local-prefixes: github.com/FreePeak/cortex

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/interfaces/rest
      linters:
        - goimports

  max-issues-per-linter: 0
  max-same-issues: 0 