run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/FreePeak/golang-mcp-server-sdk

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/interfaces/rest
      linters:
        - goimports

  max-issues-per-linter: 0
  max-same-issues: 0 